cabal: true
columns: 80
newline: lf
steps:
  - simple_align:
      cases: true
      records: true
      top_level_patterns: true
  - imports:
      align: group
      empty_list_align: right_after
      list_align: after_alias
      list_padding: module_name
      long_list_align: inline
      pad_module_names: true
      separate_lists: true
      space_surround: false
  - language_pragmas:
      align: true
      language_prefix: LANGUAGE
      remove_redundant: true
      style: vertical
  - trailing_whitespace: {}
