resolver: lts-15.13

packages:
- .

extra-deps:
- git: https://github.com/Krasjet/pandoc-utils.git
  commit: 6ace7bad512414caf703de201712dba0308dd1fe
- git: https://github.com/Krasjet/libkst.git
  commit: db46ad36f47091281efa06db14c1469236d7274c
