resolver: lts-15.13

packages:
- .

extra-deps:
- git: https://github.com/Krasjet/pandoc-utils.git
  commit: 17c77b7c352d742820076bdfa9c96deb08faa250
- git: https://github.com/Krasjet/libkst.git
  commit: 8e277c181d357d148601be7236aa4315f348e217
