{-# LANGUAGE OverloadedStrings #-}

-- | Lexer mappings in Pygments filter
--
-- **Generated code, DO NOT modify**.
module Text.Pandoc.Fltr.Pygments.Lexers (
  langMapping
) where

import qualified Data.Map as Map

import Data.Map  (Map)
import Data.Text (Text)

-- | Mapping from aliases to language name
langMapping :: Map Text Text
langMapping = Map.fromList
  [ ("abap", "ABAP")
  , ("apl", "APL")
  , ("abnf", "ABNF")
  , ("as3", "ActionScript 3")
  , ("actionscript3", "ActionScript 3")
  , ("as", "ActionScript")
  , ("actionscript", "ActionScript")
  , ("ada", "Ada")
  , ("ada95", "Ada")
  , ("ada2005", "Ada")
  , ("adl", "ADL")
  , ("agda", "Agda")
  , ("aheui", "Aheui")
  , ("alloy", "Alloy")
  , ("at", "AmbientTalk")
  , ("ambienttalk", "AmbientTalk")
  , ("ambienttalk/2", "AmbientTalk")
  , ("ampl", "Ampl")
  , ("html+ng2", "HTML + Angular2")
  , ("ng2", "Angular2")
  , ("antlr-as", "ANTLR With ActionScript Target")
  , ("antlr-actionscript", "ANTLR With ActionScript Target")
  , ("antlr-csharp", "ANTLR With C# Target")
  , ("antlr-c#", "ANTLR With C# Target")
  , ("antlr-cpp", "ANTLR With CPP Target")
  , ("antlr-java", "ANTLR With Java Target")
  , ("antlr", "ANTLR")
  , ("antlr-objc", "ANTLR With ObjectiveC Target")
  , ("antlr-perl", "ANTLR With Perl Target")
  , ("antlr-python", "ANTLR With Python Target")
  , ("antlr-ruby", "ANTLR With Ruby Target")
  , ("antlr-rb", "ANTLR With Ruby Target")
  , ("apacheconf", "ApacheConf")
  , ("aconf", "ApacheConf")
  , ("apache", "ApacheConf")
  , ("applescript", "AppleScript")
  , ("arduino", "Arduino")
  , ("aspectj", "AspectJ")
  , ("asy", "Asymptote")
  , ("asymptote", "Asymptote")
  , ("augeas", "Augeas")
  , ("autoit", "AutoIt")
  , ("ahk", "autohotkey")
  , ("autohotkey", "autohotkey")
  , ("awk", "Awk")
  , ("gawk", "Awk")
  , ("mawk", "Awk")
  , ("nawk", "Awk")
  , ("bbcbasic", "BBC Basic")
  , ("bbcode", "BBCode")
  , ("bc", "BC")
  , ("bst", "BST")
  , ("bst-pybtex", "BST")
  , ("basemake", "Base Makefile")
  , ("bash", "Bash")
  , ("sh", "Bash")
  , ("ksh", "Bash")
  , ("zsh", "Bash")
  , ("shell", "Bash")
  , ("console", "Bash Session")
  , ("shell-session", "Bash Session")
  , ("bat", "Batchfile")
  , ("batch", "Batchfile")
  , ("dosbatch", "Batchfile")
  , ("winbatch", "Batchfile")
  , ("befunge", "Befunge")
  , ("bib", "BibTeX")
  , ("bibtex", "BibTeX")
  , ("blitzbasic", "BlitzBasic")
  , ("b3d", "BlitzBasic")
  , ("bplus", "BlitzBasic")
  , ("blitzmax", "BlitzMax")
  , ("bmax", "BlitzMax")
  , ("bnf", "BNF")
  , ("boa", "Boa")
  , ("boo", "Boo")
  , ("boogie", "Boogie")
  , ("brainfuck", "Brainfuck")
  , ("bf", "Brainfuck")
  , ("bugs", "BUGS")
  , ("winbugs", "BUGS")
  , ("openbugs", "BUGS")
  , ("camkes", "CAmkES")
  , ("idl4", "CAmkES")
  , ("c", "C")
  , ("cmake", "CMake")
  , ("c-objdump", "c-objdump")
  , ("cpsa", "CPSA")
  , ("aspx-cs", "aspx-cs")
  , ("csharp", "C#")
  , ("c#", "C#")
  , ("ca65", "ca65 assembler")
  , ("cadl", "cADL")
  , ("capdl", "CapDL")
  , ("capnp", "Cap'n Proto")
  , ("cbmbas", "CBM BASIC V2")
  , ("ceylon", "Ceylon")
  , ("cfengine3", "CFEngine3")
  , ("cf3", "CFEngine3")
  , ("chai", "ChaiScript")
  , ("chaiscript", "ChaiScript")
  , ("chapel", "Chapel")
  , ("chpl", "Chapel")
  , ("charmci", "Charmci")
  , ("html+cheetah", "HTML+Cheetah")
  , ("html+spitfire", "HTML+Cheetah")
  , ("htmlcheetah", "HTML+Cheetah")
  , ("js+cheetah", "JavaScript+Cheetah")
  , ("javascript+cheetah", "JavaScript+Cheetah")
  , ("js+spitfire", "JavaScript+Cheetah")
  , ("javascript+spitfire", "JavaScript+Cheetah")
  , ("cheetah", "Cheetah")
  , ("spitfire", "Cheetah")
  , ("xml+cheetah", "XML+Cheetah")
  , ("xml+spitfire", "XML+Cheetah")
  , ("cirru", "Cirru")
  , ("clay", "Clay")
  , ("clean", "Clean")
  , ("clojure", "Clojure")
  , ("clj", "Clojure")
  , ("clojurescript", "ClojureScript")
  , ("cljs", "ClojureScript")
  , ("cobolfree", "COBOLFree")
  , ("cobol", "COBOL")
  , ("coffee-script", "CoffeeScript")
  , ("coffeescript", "CoffeeScript")
  , ("coffee", "CoffeeScript")
  , ("cfc", "Coldfusion CFC")
  , ("cfm", "Coldfusion HTML")
  , ("cfs", "cfstatement")
  , ("common-lisp", "Common Lisp")
  , ("cl", "Common Lisp")
  , ("lisp", "Common Lisp")
  , ("componentpascal", "Component Pascal")
  , ("cp", "Component Pascal")
  , ("coq", "Coq")
  , ("cpp", "C++")
  , ("c++", "C++")
  , ("cpp-objdump", "cpp-objdump")
  , ("c++-objdumb", "cpp-objdump")
  , ("cxx-objdump", "cpp-objdump")
  , ("crmsh", "Crmsh")
  , ("pcmk", "Crmsh")
  , ("croc", "Croc")
  , ("cryptol", "Cryptol")
  , ("cry", "Cryptol")
  , ("cr", "Crystal")
  , ("crystal", "Crystal")
  , ("csound-document", "Csound Document")
  , ("csound-csd", "Csound Document")
  , ("csound", "Csound Orchestra")
  , ("csound-orc", "Csound Orchestra")
  , ("csound-score", "Csound Score")
  , ("csound-sco", "Csound Score")
  , ("css+django", "CSS+Django/Jinja")
  , ("css+jinja", "CSS+Django/Jinja")
  , ("css+erb", "CSS+Ruby")
  , ("css+ruby", "CSS+Ruby")
  , ("css+genshitext", "CSS+Genshi Text")
  , ("css+genshi", "CSS+Genshi Text")
  , ("css", "CSS")
  , ("css+php", "CSS+PHP")
  , ("css+smarty", "CSS+Smarty")
  , ("cuda", "CUDA")
  , ("cu", "CUDA")
  , ("cypher", "Cypher")
  , ("cython", "Cython")
  , ("pyx", "Cython")
  , ("pyrex", "Cython")
  , ("d", "D")
  , ("d-objdump", "d-objdump")
  , ("dpatch", "Darcs Patch")
  , ("dart", "Dart")
  , ("dasm16", "DASM16")
  , ("control", "Debian Control file")
  , ("debcontrol", "Debian Control file")
  , ("delphi", "Delphi")
  , ("pas", "Delphi")
  , ("pascal", "Delphi")
  , ("objectpascal", "Delphi")
  , ("dg", "dg")
  , ("diff", "Diff")
  , ("udiff", "Diff")
  , ("django", "Django/Jinja")
  , ("jinja", "Django/Jinja")
  , ("docker", "Docker")
  , ("dockerfile", "Docker")
  , ("dtd", "DTD")
  , ("duel", "Duel")
  , ("jbst", "Duel")
  , ("jsonml+bst", "Duel")
  , ("dylan-console", "Dylan session")
  , ("dylan-repl", "Dylan session")
  , ("dylan", "Dylan")
  , ("dylan-lid", "DylanLID")
  , ("lid", "DylanLID")
  , ("ecl", "ECL")
  , ("ec", "eC")
  , ("earl-grey", "Earl Grey")
  , ("earlgrey", "Earl Grey")
  , ("eg", "Earl Grey")
  , ("easytrieve", "Easytrieve")
  , ("ebnf", "EBNF")
  , ("eiffel", "Eiffel")
  , ("iex", "Elixir iex session")
  , ("elixir", "Elixir")
  , ("ex", "Elixir")
  , ("exs", "Elixir")
  , ("elm", "Elm")
  , ("emacs", "EmacsLisp")
  , ("elisp", "EmacsLisp")
  , ("emacs-lisp", "EmacsLisp")
  , ("email", "E-mail")
  , ("eml", "E-mail")
  , ("erb", "ERB")
  , ("erlang", "Erlang")
  , ("erl", "Erlang erl session")
  , ("html+evoque", "HTML+Evoque")
  , ("evoque", "Evoque")
  , ("xml+evoque", "XML+Evoque")
  , ("ezhil", "Ezhil")
  , ("fsharp", "F#")
  , ("f#", "F#")
  , ("factor", "Factor")
  , ("fancy", "Fancy")
  , ("fy", "Fancy")
  , ("fan", "Fantom")
  , ("felix", "Felix")
  , ("flx", "Felix")
  , ("fennel", "Fennel")
  , ("fnl", "Fennel")
  , ("fish", "Fish")
  , ("fishshell", "Fish")
  , ("flatline", "Flatline")
  , ("floscript", "FloScript")
  , ("flo", "FloScript")
  , ("forth", "Forth")
  , ("fortranfixed", "FortranFixed")
  , ("fortran", "Fortran")
  , ("foxpro", "FoxPro")
  , ("vfp", "FoxPro")
  , ("clipper", "FoxPro")
  , ("xbase", "FoxPro")
  , ("freefem", "Freefem")
  , ("gap", "GAP")
  , ("glsl", "GLSL")
  , ("gas", "GAS")
  , ("asm", "GAS")
  , ("genshi", "Genshi")
  , ("kid", "Genshi")
  , ("xml+genshi", "Genshi")
  , ("xml+kid", "Genshi")
  , ("genshitext", "Genshi Text")
  , ("pot", "Gettext Catalog")
  , ("po", "Gettext Catalog")
  , ("cucumber", "Gherkin")
  , ("gherkin", "Gherkin")
  , ("gnuplot", "Gnuplot")
  , ("go", "Go")
  , ("golo", "Golo")
  , ("gooddata-cl", "GoodData-CL")
  , ("gosu", "Gosu")
  , ("gst", "Gosu Template")
  , ("groff", "Groff")
  , ("nroff", "Groff")
  , ("man", "Groff")
  , ("groovy", "Groovy")
  , ("hlsl", "HLSL")
  , ("haml", "Haml")
  , ("html+handlebars", "HTML+Handlebars")
  , ("handlebars", "Handlebars")
  , ("haskell", "Haskell")
  , ("hs", "Haskell")
  , ("hx", "Haxe")
  , ("haxe", "Haxe")
  , ("hxsl", "Haxe")
  , ("hexdump", "Hexdump")
  , ("hsail", "HSAIL")
  , ("hsa", "HSAIL")
  , ("hspec", "Hspec")
  , ("html+django", "HTML+Django/Jinja")
  , ("html+jinja", "HTML+Django/Jinja")
  , ("htmldjango", "HTML+Django/Jinja")
  , ("html+genshi", "HTML+Genshi")
  , ("html+kid", "HTML+Genshi")
  , ("html", "HTML")
  , ("html+php", "HTML+PHP")
  , ("html+smarty", "HTML+Smarty")
  , ("http", "HTTP")
  , ("haxeml", "Hxml")
  , ("hxml", "Hxml")
  , ("hylang", "Hy")
  , ("hybris", "Hybris")
  , ("hy", "Hybris")
  , ("idl", "IDL")
  , ("icon", "Icon")
  , ("idris", "Idris")
  , ("idr", "Idris")
  , ("igor", "Igor")
  , ("igorpro", "Igor")
  , ("inform6", "Inform 6")
  , ("i6", "Inform 6")
  , ("i6t", "Inform 6 template")
  , ("inform7", "Inform 7")
  , ("i7", "Inform 7")
  , ("ini", "INI")
  , ("cfg", "INI")
  , ("dosini", "INI")
  , ("io", "Io")
  , ("ioke", "Ioke")
  , ("ik", "Ioke")
  , ("irc", "IRC logs")
  , ("isabelle", "Isabelle")
  , ("j", "J")
  , ("jags", "JAGS")
  , ("jasmin", "Jasmin")
  , ("jasminxt", "Jasmin")
  , ("java", "Java")
  , ("js+django", "JavaScript+Django/Jinja")
  , ("javascript+django", "JavaScript+Django/Jinja")
  , ("js+jinja", "JavaScript+Django/Jinja")
  , ("javascript+jinja", "JavaScript+Django/Jinja")
  , ("js+erb", "JavaScript+Ruby")
  , ("javascript+erb", "JavaScript+Ruby")
  , ("js+ruby", "JavaScript+Ruby")
  , ("javascript+ruby", "JavaScript+Ruby")
  , ("js+genshitext", "JavaScript+Genshi Text")
  , ("js+genshi", "JavaScript+Genshi Text")
  , ("javascript+genshitext", "JavaScript+Genshi Text")
  , ("javascript+genshi", "JavaScript+Genshi Text")
  , ("js", "JavaScript")
  , ("javascript", "JavaScript")
  , ("js+php", "JavaScript+PHP")
  , ("javascript+php", "JavaScript+PHP")
  , ("js+smarty", "JavaScript+Smarty")
  , ("javascript+smarty", "JavaScript+Smarty")
  , ("jcl", "JCL")
  , ("jsgf", "JSGF")
  , ("json-object", "JSONBareObject")
  , ("jsonld", "JSON-LD")
  , ("json-ld", "JSON-LD")
  , ("json", "JSON")
  , ("jsp", "Java Server Page")
  , ("jlcon", "Julia console")
  , ("julia", "Julia")
  , ("jl", "Julia")
  , ("juttle", "Juttle")
  , ("juttle", "Juttle")
  , ("kal", "Kal")
  , ("kconfig", "Kconfig")
  , ("menuconfig", "Kconfig")
  , ("linux-config", "Kconfig")
  , ("kernel-config", "Kconfig")
  , ("kmsg", "Kernel log")
  , ("dmesg", "Kernel log")
  , ("koka", "Koka")
  , ("kotlin", "Kotlin")
  , ("lsl", "LSL")
  , ("css+lasso", "CSS+Lasso")
  , ("html+lasso", "HTML+Lasso")
  , ("js+lasso", "JavaScript+Lasso")
  , ("javascript+lasso", "JavaScript+Lasso")
  , ("lasso", "Lasso")
  , ("lassoscript", "Lasso")
  , ("xml+lasso", "XML+Lasso")
  , ("lean", "Lean")
  , ("less", "LessCss")
  , ("lighty", "Lighttpd configuration file")
  , ("lighttpd", "Lighttpd configuration file")
  , ("limbo", "Limbo")
  , ("liquid", "liquid")
  , ("lagda", "Literate Agda")
  , ("literate-agda", "Literate Agda")
  , ("lcry", "Literate Cryptol")
  , ("literate-cryptol", "Literate Cryptol")
  , ("lcryptol", "Literate Cryptol")
  , ("lhs", "Literate Haskell")
  , ("literate-haskell", "Literate Haskell")
  , ("lhaskell", "Literate Haskell")
  , ("lidr", "Literate Idris")
  , ("literate-idris", "Literate Idris")
  , ("lidris", "Literate Idris")
  , ("live-script", "LiveScript")
  , ("livescript", "LiveScript")
  , ("llvm", "LLVM")
  , ("llvm-mir-body", "LLVM-MIR Body")
  , ("llvm-mir", "LLVM-MIR")
  , ("logos", "Logos")
  , ("logtalk", "Logtalk")
  , ("lua", "Lua")
  , ("mime", "MIME")
  , ("moocode", "MOOCode")
  , ("moo", "MOOCode")
  , ("doscon", "MSDOS Session")
  , ("make", "Makefile")
  , ("makefile", "Makefile")
  , ("mf", "Makefile")
  , ("bsdmake", "Makefile")
  , ("css+mako", "CSS+Mako")
  , ("html+mako", "HTML+Mako")
  , ("js+mako", "JavaScript+Mako")
  , ("javascript+mako", "JavaScript+Mako")
  , ("mako", "Mako")
  , ("xml+mako", "XML+Mako")
  , ("maql", "MAQL")
  , ("md", "markdown")
  , ("mask", "Mask")
  , ("mason", "Mason")
  , ("mathematica", "Mathematica")
  , ("mma", "Mathematica")
  , ("nb", "Mathematica")
  , ("matlab", "Matlab")
  , ("matlabsession", "Matlab session")
  , ("minid", "MiniD")
  , ("ms", "MiniScript")
  , ("miniscript", "MiniScript")
  , ("modelica", "Modelica")
  , ("modula2", "Modula-2")
  , ("m2", "Modula-2")
  , ("trac-wiki", "MoinMoin/Trac Wiki markup")
  , ("moin", "MoinMoin/Trac Wiki markup")
  , ("monkey", "Monkey")
  , ("monte", "Monte")
  , ("moon", "MoonScript")
  , ("moonscript", "MoonScript")
  , ("mosel", "Mosel")
  , ("css+mozpreproc", "CSS+mozpreproc")
  , ("mozhashpreproc", "mozhashpreproc")
  , ("javascript+mozpreproc", "Javascript+mozpreproc")
  , ("mozpercentpreproc", "mozpercentpreproc")
  , ("xul+mozpreproc", "XUL+mozpreproc")
  , ("mql", "MQL")
  , ("mq4", "MQL")
  , ("mq5", "MQL")
  , ("mql4", "MQL")
  , ("mql5", "MQL")
  , ("mscgen", "Mscgen")
  , ("msc", "Mscgen")
  , ("mupad", "MuPAD")
  , ("mxml", "MXML")
  , ("mysql", "MySQL")
  , ("css+myghty", "CSS+Myghty")
  , ("html+myghty", "HTML+Myghty")
  , ("js+myghty", "JavaScript+Myghty")
  , ("javascript+myghty", "JavaScript+Myghty")
  , ("myghty", "Myghty")
  , ("xml+myghty", "XML+Myghty")
  , ("ncl", "NCL")
  , ("nsis", "NSIS")
  , ("nsi", "NSIS")
  , ("nsh", "NSIS")
  , ("nasm", "NASM")
  , ("objdump-nasm", "objdump-nasm")
  , ("nemerle", "Nemerle")
  , ("nesc", "nesC")
  , ("newlisp", "NewLisp")
  , ("newspeak", "Newspeak")
  , ("nginx", "Nginx configuration file")
  , ("nim", "Nimrod")
  , ("nimrod", "Nimrod")
  , ("nit", "Nit")
  , ("nixos", "Nix")
  , ("nix", "Nix")
  , ("notmuch", "Notmuch")
  , ("nusmv", "NuSMV")
  , ("numpy", "NumPy")
  , ("objdump", "objdump")
  , ("objective-c", "Objective-C")
  , ("objectivec", "Objective-C")
  , ("obj-c", "Objective-C")
  , ("objc", "Objective-C")
  , ("objective-c++", "Objective-C++")
  , ("objectivec++", "Objective-C++")
  , ("obj-c++", "Objective-C++")
  , ("objc++", "Objective-C++")
  , ("objective-j", "Objective-J")
  , ("objectivej", "Objective-J")
  , ("obj-j", "Objective-J")
  , ("objj", "Objective-J")
  , ("ocaml", "OCaml")
  , ("octave", "Octave")
  , ("odin", "ODIN")
  , ("ooc", "Ooc")
  , ("opa", "Opa")
  , ("openedge", "OpenEdge ABL")
  , ("abl", "OpenEdge ABL")
  , ("progress", "OpenEdge ABL")
  , ("pacmanconf", "PacmanConf")
  , ("pan", "Pan")
  , ("parasail", "ParaSail")
  , ("pawn", "Pawn")
  , ("peg", "PEG")
  , ("perl6", "Perl6")
  , ("pl6", "Perl6")
  , ("raku", "Perl6")
  , ("perl", "Perl")
  , ("pl", "Perl")
  , ("php", "PHP")
  , ("php3", "PHP")
  , ("php4", "PHP")
  , ("php5", "PHP")
  , ("pig", "Pig")
  , ("pike", "Pike")
  , ("pkgconfig", "PkgConfig")
  , ("plpgsql", "PL/pgSQL")
  , ("pony", "Pony")
  , ("postscript", "PostScript")
  , ("postscr", "PostScript")
  , ("psql", "PostgreSQL console (psql)")
  , ("postgresql-console", "PostgreSQL console (psql)")
  , ("postgres-console", "PostgreSQL console (psql)")
  , ("postgresql", "PostgreSQL SQL dialect")
  , ("postgres", "PostgreSQL SQL dialect")
  , ("pov", "POVRay")
  , ("powershell", "PowerShell")
  , ("posh", "PowerShell")
  , ("ps1", "PowerShell")
  , ("psm1", "PowerShell")
  , ("ps1con", "PowerShell Session")
  , ("praat", "Praat")
  , ("prolog", "Prolog")
  , ("properties", "Properties")
  , ("jproperties", "Properties")
  , ("protobuf", "Protocol Buffer")
  , ("proto", "Protocol Buffer")
  , ("pug", "Pug")
  , ("jade", "Pug")
  , ("puppet", "Puppet")
  , ("pypylog", "PyPy Log")
  , ("pypy", "PyPy Log")
  , ("python2", "Python 2.x")
  , ("py2", "Python 2.x")
  , ("py2tb", "Python 2.x Traceback")
  , ("pycon", "Python console session")
  , ("python", "Python")
  , ("py", "Python")
  , ("sage", "Python")
  , ("python3", "Python")
  , ("py3", "Python")
  , ("pytb", "Python Traceback")
  , ("py3tb", "Python Traceback")
  , ("qbasic", "QBasic")
  , ("basic", "QBasic")
  , ("qvto", "QVTO")
  , ("qvt", "QVTO")
  , ("qml", "QML")
  , ("qbs", "QML")
  , ("rconsole", "RConsole")
  , ("rout", "RConsole")
  , ("rnc", "Relax-NG Compact")
  , ("rng-compact", "Relax-NG Compact")
  , ("spec", "RPMSpec")
  , ("racket", "Racket")
  , ("rkt", "Racket")
  , ("ragel-c", "Ragel in C Host")
  , ("ragel-cpp", "Ragel in CPP Host")
  , ("ragel-d", "Ragel in D Host")
  , ("ragel-em", "Embedded Ragel")
  , ("ragel-java", "Ragel in Java Host")
  , ("ragel", "Ragel")
  , ("ragel-objc", "Ragel in Objective C Host")
  , ("ragel-ruby", "Ragel in Ruby Host")
  , ("ragel-rb", "Ragel in Ruby Host")
  , ("raw", "Raw token data")
  , ("rd", "Rd")
  , ("reason", "ReasonML")
  , ("reasonml", "ReasonML")
  , ("rebol", "REBOL")
  , ("red", "Red")
  , ("red/system", "Red")
  , ("redcode", "Redcode")
  , ("registry", "reg")
  , ("resource", "ResourceBundle")
  , ("resourcebundle", "ResourceBundle")
  , ("rexx", "Rexx")
  , ("arexx", "Rexx")
  , ("rhtml", "RHTML")
  , ("html+erb", "RHTML")
  , ("html+ruby", "RHTML")
  , ("ride", "Ride")
  , ("roboconf-graph", "Roboconf Graph")
  , ("roboconf-instances", "Roboconf Instances")
  , ("robotframework", "RobotFramework")
  , ("rql", "RQL")
  , ("rsl", "RSL")
  , ("rst", "reStructuredText")
  , ("rest", "reStructuredText")
  , ("restructuredtext", "reStructuredText")
  , ("rts", "TrafficScript")
  , ("trafficscript", "TrafficScript")
  , ("rbcon", "Ruby irb session")
  , ("irb", "Ruby irb session")
  , ("rb", "Ruby")
  , ("ruby", "Ruby")
  , ("duby", "Ruby")
  , ("rust", "Rust")
  , ("rs", "Rust")
  , ("sas", "SAS")
  , ("splus", "S")
  , ("s", "S")
  , ("r", "S")
  , ("sml", "Standard ML")
  , ("sarl", "SARL")
  , ("sass", "Sass")
  , ("scala", "Scala")
  , ("scaml", "Scaml")
  , ("scdoc", "scdoc")
  , ("scd", "scdoc")
  , ("scheme", "Scheme")
  , ("scm", "Scheme")
  , ("scilab", "Scilab")
  , ("scss", "SCSS")
  , ("shexc", "ShExC")
  , ("shex", "ShExC")
  , ("shen", "Shen")
  , ("sieve", "Sieve")
  , ("silver", "Silver")
  , ("slash", "Slash")
  , ("slim", "Slim")
  , ("slurm", "Slurm")
  , ("sbatch", "Slurm")
  , ("smali", "Smali")
  , ("smalltalk", "Smalltalk")
  , ("squeak", "Smalltalk")
  , ("st", "Smalltalk")
  , ("sgf", "SmartGameFormat")
  , ("smarty", "Smarty")
  , ("snobol", "Snobol")
  , ("snowball", "Snowball")
  , ("solidity", "Solidity")
  , ("sp", "SourcePawn")
  , ("sourceslist", "Debian Sourcelist")
  , ("sources.list", "Debian Sourcelist")
  , ("debsources", "Debian Sourcelist")
  , ("sparql", "SPARQL")
  , ("sql", "SQL")
  , ("sqlite3", "sqlite3con")
  , ("squidconf", "SquidConf")
  , ("squid.conf", "SquidConf")
  , ("squid", "SquidConf")
  , ("ssp", "Scalate Server Page")
  , ("stan", "Stan")
  , ("stata", "Stata")
  , ("do", "Stata")
  , ("sc", "SuperCollider")
  , ("supercollider", "SuperCollider")
  , ("swift", "Swift")
  , ("swig", "SWIG")
  , ("systemverilog", "systemverilog")
  , ("sv", "systemverilog")
  , ("tap", "TAP")
  , ("toml", "TOML")
  , ("tads3", "TADS 3")
  , ("tasm", "TASM")
  , ("tcl", "Tcl")
  , ("tcsh", "Tcsh")
  , ("csh", "Tcsh")
  , ("tcshcon", "Tcsh Session")
  , ("tea", "Tea")
  , ("ttl", "Tera Term macro")
  , ("teraterm", "Tera Term macro")
  , ("teratermmacro", "Tera Term macro")
  , ("termcap", "Termcap")
  , ("terminfo", "Terminfo")
  , ("terraform", "Terraform")
  , ("tf", "Terraform")
  , ("tex", "TeX")
  , ("latex", "TeX")
  , ("text", "Text only")
  , ("thrift", "Thrift")
  , ("todotxt", "Todotxt")
  , ("tsql", "Transact-SQL")
  , ("t-sql", "Transact-SQL")
  , ("treetop", "Treetop")
  , ("turtle", "Turtle")
  , ("html+twig", "HTML+Twig")
  , ("twig", "Twig")
  , ("ts", "TypeScript")
  , ("typescript", "TypeScript")
  , ("typoscriptcssdata", "TypoScriptCssData")
  , ("typoscripthtmldata", "TypoScriptHtmlData")
  , ("typoscript", "TypoScript")
  , ("ucode", "ucode")
  , ("unicon", "Unicon")
  , ("urbiscript", "UrbiScript")
  , ("usd", "USD")
  , ("usda", "USD")
  , ("vbscript", "VBScript")
  , ("vcl", "VCL")
  , ("vclsnippets", "VCLSnippets")
  , ("vclsnippet", "VCLSnippets")
  , ("vctreestatus", "VCTreeStatus")
  , ("vgl", "VGL")
  , ("vala", "Vala")
  , ("vapi", "Vala")
  , ("aspx-vb", "aspx-vb")
  , ("vb.net", "VB.net")
  , ("vbnet", "VB.net")
  , ("html+velocity", "HTML+Velocity")
  , ("velocity", "Velocity")
  , ("xml+velocity", "XML+Velocity")
  , ("verilog", "verilog")
  , ("v", "verilog")
  , ("vhdl", "vhdl")
  , ("vim", "VimL")
  , ("wdiff", "WDiff")
  , ("webidl", "Web IDL")
  , ("whiley", "Whiley")
  , ("x10", "X10")
  , ("xten", "X10")
  , ("xquery", "XQuery")
  , ("xqy", "XQuery")
  , ("xq", "XQuery")
  , ("xql", "XQuery")
  , ("xqm", "XQuery")
  , ("xml+django", "XML+Django/Jinja")
  , ("xml+jinja", "XML+Django/Jinja")
  , ("xml+erb", "XML+Ruby")
  , ("xml+ruby", "XML+Ruby")
  , ("xml", "XML")
  , ("xml+php", "XML+PHP")
  , ("xml+smarty", "XML+Smarty")
  , ("xorg.conf", "Xorg")
  , ("xslt", "XSLT")
  , ("xtend", "Xtend")
  , ("extempore", "xtlang")
  , ("yaml+jinja", "YAML+Jinja")
  , ("salt", "YAML+Jinja")
  , ("sls", "YAML+Jinja")
  , ("yaml", "YAML")
  , ("zeek", "Zeek")
  , ("bro", "Zeek")
  , ("zephir", "Zephir")
  , ("zig", "Zig")
  ]
